### ISSUE TITLE
Add more accents to libs\english.@

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ConorOBrien-Foxx/Attache#37]
To include:

* horns
* macrons
* tildes
* cedillas
* hooks
  * palatal hooks
  * left hooks
  * retroflex hooks
  * middle hooks
  * fishhooks
  * above hooks
* probably more I'm missing

# Editing

Open up `libs\english.@` and look at the examples there. Add all accents in Unicode for a certain accent type (e.g. [the cedilla](https://unicodelookup.com/#cedilla/1)) paired after their un-accented counterpart. Then, add a few lines to the end of the aforementioned file that follows this pattern:

```
<accent_name> := "accents"
<accent_name>_add := hash_pair[accent_name]
```

For example, for "graves":

```
graves := "AÀEÈIÌOÒUÙaàeèiìoòuùÜǛüǜNǸnǹЕЀИЍеѐиѝĒḔēḕŌṐōṑWẀwẁÂẦâầĂẰăằÊỀêềÔỒôồƠỜơờƯỪưừYỲyỳ"
graves_add := hash_pair[graves]
```

...and that's it!

**Comment by somebody1234** [comment]
will attempt to do this, using script magic, posting here for reference purposes
```js
accented = $.makeArray($('td.char')).map(e=>e.innerText)
nonAccented = $.makeArray($('td.uni')).map(e=>/and/.test(e.innerText)?undefined:/capital/.test(e.innerText)?e.innerText.match(/letter (.) /)[1].toUpperCase():(e.innerText.match(/letter (.) /)||[])[1])
for(i=0,s='';i<nonAccented.length;i++)if(nonAccented[i])s+=nonAccented[i]+accented[i]
s
```

**Comment by somebody1234** [comment]
What about combined accents? e.g. horn and acute

**Comment by somebody1234** [comment]
Also, looks like no english letters have middle hook variants
