### ISSUE TITLE
Currying is broken for abstracts nested within operators

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ConorOBrien-Foxx/Attache#38]
### Expected Behaviour

```
Print<~ _2 + ",", _1 ~>["John"]["Smith"]
?? Smith, John
```

### Actual Behaviour

```
Print<~ _2 + ",", _1 ~>["John"]["Smith"]
?? some error
```

**Comment by ConorOBrien-Foxx** [comment]
this is because abstract replacement isn't recursively applied. this should be easily fixed once the relevant section of code is identified

**Comment by somebody1234** [comment]
It appears to fallback to `@saved` if it's out of bounds, what does `@saved` do?

**Comment by ConorOBrien-Foxx** [comment]
I think that's a vestige of old-style attache. Abstracts used to be "saved" values, and I think I messed up propagating those values somewhere.

**Comment by somebody1234** [comment]
Probably not useful, but that example you posted never even makes it to `make_curry`

**Comment by ConorOBrien-Foxx** [comment]
curry literals and scoping are the two most-broken things rn

**Comment by somebody1234** [comment]
Looks like... line 616? `args.each` in `make_curry` doesn't check children of nodes?

**Comment by somebody1234** [comment]
Now... how to check if a node has children

**Comment by ConorOBrien-Foxx** [comment]
check if `el` is a `Node`, and if it is, it'll have a property `el.children`

**Comment by somebody1234** [comment]
Yeah just realized that lol. On the plus side, almost finished :D

**Comment by ConorOBrien-Foxx** [comment]
\o/

**Comment by somebody1234** [comment]
Any way to clone a node?

**Comment by somebody1234** [comment]
Any examples/testcases/MCVEs on how scoping is broken? I _think_ scoping should be relatively easy to fix, but it _may_ require some refactoring

**Comment by ConorOBrien-Foxx** [comment]
yeah, I'll work on that

**Comment by ConorOBrien-Foxx** [comment]
[This is the first thing that comes to mind](https://tio.run/##SywpSUzOSP3/P7cyKDEvJT83uiJWwcpWAcqJVdBSqODics5JLC72S8xNTYkOycjMS49VqOZSAILc0pwSBT1bhXhDMBeqqTIWJKYBFgKBgKLMvJLoSh2w8lhra7gE3M5KoDVgSbCUJlctF1duJdgmkFvAjGjTWC6IQVAZNK4e1Cjj2Nj//wE) (has to do with classes and functions being evaluated in the context they're called from), I'm having trouble finding the old scoping bugs.

**Comment by somebody1234** [comment]
Hmm... so what you really want is to pass the context when the class/function is created, right? Although it might be a bit more complicated for e.g. nested functions

**Comment by ConorOBrien-Foxx** [comment]
yup... something like that

**Comment by somebody1234** [comment]
So more precisely... during assignment, any token that's not an argument should be replaced with its value? What if something is defined later? 🤔 Does/should Attache behave like Mathematica and use its value at the time it is called?

While we're on the topic: Is Attache intended to be symbolic? (Obviously, it isn't right now)

**Comment by somebody1234** [comment]
Also, found the relevant section of the source re: function value replacement - `AtState.rb#959`, `set_variable` when `Node === var`

**Comment by somebody1234** [comment]
Okay... so it's harder than I thought. You need to be able to figure out how to not replace args in nested functions

**Comment by somebody1234** [comment]
I wonder if there's any cleaner way than recursing when you find `->` + `:make_lambda`, `:=` or `.=`?

Also, `make_lambda` feels hacky, I don't think this method will work inside lambdas as it currently is without parsing the lambda again

EDIT: You also need to somehow make recursive functions work
EDIT 2: I think scopes need a major refactor - tokens should be converted to a lambda returning the function
EDIT 3: Ok :| I'm going to try the simplest way first, just found where the lambda is attached to the scope
