### ISSUE TITLE
Syntax: overloading `$` syntax

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ConorOBrien-Foxx/Attache#41]
_overview_

- [x] `$` functions (anonymous named lambdas)
- [x] `$` and `$$` numbers (command line arguments)
- [x] `$` quotes: format strings
- [x] `$` paren: nested strings (not going to be implemented)

**Note:** Since `$` is a valid noun, `$<operator>` cannot be overloaded.

`$` functions: `${}` should be a lambda which takes 1 to 3 parameters, referenced as `x`, `y`, `z`. E.g:

```
add2 := ${ x + y }
fit := ${ (x + y + z) / 2 }
```

`$` numbers: `$N` should refer to the `N`th command line argument. (`$0` is the file name, perhaps.)

```
$ cat test.@
Print["Hello, " + $1 + "!"]
$ attache test.@ "John"
Hello, John!
```

`$$` numbers: `$$N` should refer to the `N`th-to-last command line argument.

```
$ cat test.@
Print[$1, "and", $2, ";", $$0, "and", $$1]
$ attache test.@ "first" "second" "third" "forth"
first and second ; fourth and third
$ attache test.@ "first" "second" "third"
first and second ; third and second
```

`$` quotes: formatted strings.

```
Print[$"My name is john."]
?? My name is john.
Print[$"lol: ${2+2}"]
?? lol: 4
```

`$` parentheses: nested strings

```
Print[$(Hello, World!)]
?? Hello, World!
Print[$(This is a nested string: $(hiya)!)]
?? This is a nested string: $(hiya)!
$(asdf)asdf)
?? syntax error
$(   ()   )
?? syntax error
$(   (\)   )
?? ok
```

**Comment by somebody1234** [comment]
:|

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234 thank you for the insightful feedback :P

**Comment by ConorOBrien-Foxx** [comment]
Format strings have been implemented as of #42 . Nested strings are an improbable addition, as they add little to the language. Arguments should be implemented shortly.

**Comment by somebody1234** [comment]
make this a checklist pls

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234 it is now a checklist

**Comment by somebody1234** [comment]
> shortly

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234 :P
