### ISSUE TITLE
Option for AST printing without color

### ISSUE THREAD

**Issue by somebody1234** [ConorOBrien-Foxx/Attache#44]

**Comment by somebody1234** [comment]
Could probably do this? But I have no idea what's the best way to implement it in terms of CLI

**Comment by somebody1234** [comment]
Hmm. This seems not too hard to implement, just need input @ConorOBrien-Foxx 😛

**Comment by ConorOBrien-Foxx** [comment]
I'm so bad with GH comments sorry XD I'll look into it after I tidy up a commit I'm working on

**Comment by ConorOBrien-Foxx** [comment]
I think `-A`/`--ast-no-color` should work fine

**Comment by somebody1234** [comment]
Hmm. Would it be okay to add more colors to AST output in the same commit 🤔

**Comment by ConorOBrien-Foxx** [comment]
I don't see why not

**Comment by somebody1234** [comment]
Hold on, there appears to be a circular reference

EDIT: Now fixed

**Comment by somebody1234** [comment]
Using dark colors instead of light makes it a bit hard to see on Cloud9 IDE, but if it's readable enough on your terminal it should be fine since Cloud9 uses dark blue for its terminal background

**Comment by somebody1234** [comment]
Wait... still wrong
