### ISSUE TITLE
Add `Commonest` and related functions

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ConorOBrien-Foxx/Attache#45]
`Commonest[x]` - returns the most frequent-occurring elements in `x`

`Commonest[ [1, 2, 3, 3, 2, 4] ] == [2, 3]`

`Commonest[x, n]` - returns the `n`th most common elements. If `n < 0`, then yields the `(-n)`th least common element.

```
arr := [9, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 1, 2, 2]
Commonest[arr, 1] == [5]
Commonest[arr, 2] == [6]
Commonest[arr, 3] == [7]
Commonest[arr, 4] == [8, 2]
Commonest[arr, 5] == [9, 1]
Commonest[arr, -1] == [9, 1]
Commonest[arr, 2:4] == [ [6], [7], [8, 2] ]
```

maybe a frequency table/histogram function as well

**Comment by somebody1234** [comment]
Hmm. So this is different from Mathematica's?
