### ISSUE TITLE
Problem with quote strings `$"..."`

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ConorOBrien-Foxx/Attache#53]
### Expected vs. Actual Behaviour

    Print[""""]                    ?? ✅ expected: "      actual: "
    Print[$""""]                   ?? ✅ expected: "      actual: "
    Print[]
    Print["${1+2}"]                ?? ✅ expected: ${1+2} actual: ${1+2}
    Print[$"${1+2}"]               ?? ✅ expected: 3      actual: 3
    Print[]
    Print["3"""]                   ?? ✅ expected: 3"     actual: 3"
    Print[$"3"""]                  ?? ✅ expected: 3"     actual: 3"
    Print[$"${1+2}"""]             ?? ❌ expected: 3"     actual: 3""
    Print[]
    Print["""3"]                   ?? ✅ expected: "3     actual: "3
    Print[$"""3"]                  ?? ✅ expected: "3     actual: "3
    Print[$"""${1+2}"]             ?? ❌ expected: "3     actual: ""3
    Print[]
    Print["\x23"]                  ?? ✅ expected: #      actual: #
    Print[$"\x23"]                 ?? ❌ expected: #      actual: \x23

[Try it online!][TIO-jsp070az]

[TIO-jsp070az]: https://tio.run/##SywpSUzOSP3/P6AoM68kWgkIYhWwAHt7hUdzWhVSKwpSk0tSU6wUlCDiicklpYk5QC4XxAAVXCYQa0AslFZSqTbUNqrFNAvDIIhCuEEQLtw5OIzBMMUY1TnG6M4xJtZfxkqoBiFCBocRJJgA9Qy6MSAT5vbgMwEjdJWAriEumoxRo8kYKaKNifIOPhOwxg6Gd9BNUMKInZgKI@Ico4wazcpwt@AwAcMtaAaAtP3/DwA "Attache – Try It Online"

### How to Reproduce

Found in default behavior.

**Comment by somebody1234** [comment]
I'm going to try working on this, I guess. Seems like a really easy fix, if I can get Attache running that is...

EDIT: Found the issue getting it to run. pls change hashbang to `#/usr/bin/env ruby` tyvm

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234 on it

edit - shouldn't it be `#!/usr/bin/env ruby`?

**Comment by somebody1234** [comment]
yes >_>

btw, what's `format_string_bare`?

**Comment by ConorOBrien-Foxx** [comment]
`format_string_bare` is a format string with no formatting in it, like `$"hello!"`. Compare the outputs of `attache -t`:

```
C:\Users\conorob\Programming\attache (master -> origin)
λ echo $"hello!" | attache -ti
[tokenize]
0    1:1 (0)     format_string_bare    "$\"hello!\""
1    1:10 (9)    whitespace            " \n"

C:\Users\conorob\Programming\attache (master -> origin)
λ echo $"hel${3+4}lo!" | attache -ti
[tokenize]
0    1:1 (0)      format_string_begin    "$\"hel${"
1    1:8 (7)      number                 "3"
2    1:9 (8)      operator               "+"
3    1:10 (9)     number                 "4"
4    1:11 (10)    format_string_end      "}lo!\""
5    1:16 (15)    whitespace             " \n"
```

**Comment by somebody1234** [comment]
Yeah that's part of the problem, you're handling `format_string_bare` as `raw_string` not similar to `string`

**Comment by ConorOBrien-Foxx** [comment]
odd, the problem seems to be in `format_string_(begin|end)`

**Comment by somebody1234** [comment]
Nope, fixed

**Comment by somebody1234** [comment]
Wow, that was quick O_o
